// registry/src/react/examples/ai-stream-content/toolbar.tsx
'use client'

import { streamContent } from '@prosekit/ai'
import { useEditor } from 'prosekit/react'
import { useCallback, useEffect, useRef, useState, type FormEvent } from 'react'

import type { EditorExtension } from './extension.ts'
import { streamFromOpenAI } from './llm.ts'

const API_KEY_STORAGE_KEY = 'prosekit-stream-content-api-key'
const MODEL_STORAGE_KEY = 'prosekit-stream-content-model'
const ENDPOINT_STORAGE_KEY = 'prosekit-stream-content-endpoint'
const DEFAULT_MODEL = 'gpt-4o-mini'

function readStorage(key: string, fallback = ''): string {
  if (typeof window === 'undefined') return fallback
  try {
    return window.localStorage.getItem(key) ?? fallback
  } catch {
    return fallback
  }
}

function writeStorage(key: string, value: string): void {
  if (typeof window === 'undefined') return
  try {
    window.localStorage.setItem(key, value)
  } catch {
    // Storage might be disabled; ignore.
  }
}

export default function Toolbar() {
  const editor = useEditor<EditorExtension>({ update: false })
  const [apiKey, setApiKey] = useState(() => readStorage(API_KEY_STORAGE_KEY))
  const [model, setModel] = useState(() => readStorage(MODEL_STORAGE_KEY, DEFAULT_MODEL))
  const [endpoint, setEndpoint] = useState(() => readStorage(ENDPOINT_STORAGE_KEY))
  const [prompt, setPrompt] = useState('Write a short article about prosemirror.')
  const [streaming, setStreaming] = useState(false)
  const abortRef = useRef<AbortController | null>(null)

  useEffect(() => writeStorage(API_KEY_STORAGE_KEY, apiKey), [apiKey])
  useEffect(() => writeStorage(MODEL_STORAGE_KEY, model), [model])
  useEffect(() => writeStorage(ENDPOINT_STORAGE_KEY, endpoint), [endpoint])

  const run = useCallback(
    async (event: FormEvent) => {
      event.preventDefault()
      if (!apiKey || !endpoint || !prompt || streaming) return

      const controller = new AbortController()
      abortRef.current = controller
      setStreaming(true)

      const { from, to } = editor.view.state.selection
      try {
        await streamContent(editor.view, {
          from,
          to,
          signal: controller.signal,
          onStream: (write) =>
            streamFromOpenAI({
              endpoint,
              apiKey,
              model: model || DEFAULT_MODEL,
              prompt,
              write,
              signal: controller.signal,
            }),
        })
      } catch (error) {
        if ((error as { name?: string })?.name !== 'AbortError') {
          console.error('streamContent failed:', error)
        }
      } finally {
        if (abortRef.current === controller) abortRef.current = null
        setStreaming(false)
      }
    },
    [editor, apiKey, model, endpoint, prompt, streaming],
  )

  const stop = useCallback(() => {
    abortRef.current?.abort()
  }, [])

  return (
    <form onSubmit={run} className="CSS_TOOLBAR not-content flex-col items-stretch gap-2">
      <input
        type="url"
        autoComplete="off"
        spellCheck={false}
        placeholder="API endpoint URL (stored in localStorage)"
        value={endpoint}
        onChange={(e) => setEndpoint(e.target.value)}
        className="px-2 py-1 rounded border border-gray-300 dark:border-gray-700 bg-transparent text-sm w-full"
      />
      <input
        type="password"
        autoComplete="off"
        spellCheck={false}
        placeholder="API key (stored in localStorage)"
        value={apiKey}
        onChange={(e) => setApiKey(e.target.value)}
        className="px-2 py-1 rounded border border-gray-300 dark:border-gray-700 bg-transparent text-sm w-full"
      />
      <div className="flex gap-2 items-center w-full">
        <input
          type="text"
          spellCheck={false}
          placeholder={`Model (default: ${DEFAULT_MODEL})`}
          value={model}
          onChange={(e) => setModel(e.target.value)}
          className="px-2 py-1 rounded border border-gray-300 dark:border-gray-700 bg-transparent text-sm w-40 shrink-0"
        />
        <input
          type="text"
          placeholder="Prompt the AI…"
          value={prompt}
          onChange={(e) => setPrompt(e.target.value)}
          className="px-2 py-1 rounded border border-gray-300 dark:border-gray-700 bg-transparent text-sm flex-1"
        />
        {streaming
          ? (
            <button
              type="button"
              onClick={stop}
              className="px-3 py-1 rounded bg-red-600 text-white text-sm hover:bg-red-700"
            >
              Stop
            </button>
          )
          : (
            <button
              type="submit"
              disabled={!apiKey || !endpoint || !prompt}
              className="px-3 py-1 rounded bg-blue-600 text-white text-sm hover:bg-blue-700 disabled:opacity-40 disabled:cursor-not-allowed"
            >
              Generate
            </button>
          )}
      </div>
    </form>
  )
}

// registry/src/lit/examples/ai-stream-content/toolbar.ts
import { ContextConsumer } from '@lit/context'
import { streamContent } from '@prosekit/ai'
import { html, LitElement, nothing } from 'lit'

import { editorContext } from '../../ui/editor-context.ts'

const API_KEY_STORAGE_KEY = 'prosekit-stream-content-api-key'
const MODEL_STORAGE_KEY = 'prosekit-stream-content-model'
const ENDPOINT_STORAGE_KEY = 'prosekit-stream-content-endpoint'
const DEFAULT_MODEL = 'gpt-4o-mini'

function readStorage(key: string, fallback = ''): string {
  if (typeof window === 'undefined') return fallback
  try {
    return window.localStorage.getItem(key) ?? fallback
  } catch {
    return fallback
  }
}

function writeStorage(key: string, value: string): void {
  if (typeof window === 'undefined') return
  try {
    window.localStorage.setItem(key, value)
  } catch {
    // Storage might be disabled; ignore.
  }
}

export class LitAiStreamContentToolbar extends LitElement {
  static override properties = {
    apiKey: { state: true },
    model: { state: true },
    endpoint: { state: true },
    prompt: { state: true },
    streaming: { state: true },
  }

  private apiKey = ''
  private model = DEFAULT_MODEL
  private endpoint = ''
  private prompt = 'Write a short article about prosemirror.'
  private streaming = false
  private abortController: AbortController | null = null

  private editorConsumer = new ContextConsumer(this, {
    context: editorContext,
    subscribe: true,
  })

  override createRenderRoot() {
    return this
  }

  override connectedCallback() {
    super.connectedCallback()
    this.apiKey = readStorage(API_KEY_STORAGE_KEY)
    this.model = readStorage(MODEL_STORAGE_KEY, DEFAULT_MODEL)
    this.endpoint = readStorage(ENDPOINT_STORAGE_KEY)
    this.classList.add('contents')
  }

  private onApiKeyInput = (event: Event): void => {
    this.apiKey = (event.target as HTMLInputElement).value
    writeStorage(API_KEY_STORAGE_KEY, this.apiKey)
  }

  private onModelInput = (event: Event): void => {
    this.model = (event.target as HTMLInputElement).value
    writeStorage(MODEL_STORAGE_KEY, this.model)
  }

  private onEndpointInput = (event: Event): void => {
    this.endpoint = (event.target as HTMLInputElement).value
    writeStorage(ENDPOINT_STORAGE_KEY, this.endpoint)
  }

  private onPromptInput = (event: Event): void => {
    this.prompt = (event.target as HTMLInputElement).value
  }

  private onSubmit = async (event: Event): Promise<void> => {
    event.preventDefault()
    const editor = this.editorConsumer.value
    if (!editor || !this.apiKey || !this.endpoint || !this.prompt || this.streaming) return

    const controller = new AbortController()
    this.abortController = controller
    this.streaming = true

    const { from, to } = editor.view.state.selection
    try {
      const { streamFromOpenAI } = await import('./llm.ts')
      await streamContent(editor.view, {
        from,
        to,
        signal: controller.signal,
        onStream: (write) =>
          streamFromOpenAI({
            endpoint: this.endpoint,
            apiKey: this.apiKey,
            model: this.model || DEFAULT_MODEL,
            prompt: this.prompt,
            write,
            signal: controller.signal,
          }),
      })
    } catch (error) {
      if ((error as { name?: string })?.name !== 'AbortError') {
        console.error('streamContent failed:', error)
      }
    } finally {
      if (this.abortController === controller) this.abortController = null
      this.streaming = false
    }
  }

  private onStop = (): void => {
    this.abortController?.abort()
  }

  override render() {
    const editor = this.editorConsumer.value
    if (!editor) return nothing

    const inputCls =
      'px-2 py-1 rounded border border-gray-300 dark:border-gray-700 bg-transparent text-sm'

    return html`
      <form @submit=${this.onSubmit} class="CSS_TOOLBAR not-content flex-col items-stretch gap-2">
        <input
          type="url"
          autocomplete="off"
          spellcheck="false"
          placeholder="API endpoint URL (stored in localStorage)"
          .value=${this.endpoint}
          @input=${this.onEndpointInput}
          class="${inputCls} w-full"
        />
        <input
          type="password"
          autocomplete="off"
          spellcheck="false"
          placeholder="API key (stored in localStorage)"
          .value=${this.apiKey}
          @input=${this.onApiKeyInput}
          class="${inputCls} w-full"
        />
        <div class="flex gap-2 items-center w-full">
          <input
            type="text"
            spellcheck="false"
            placeholder="Model (default: ${DEFAULT_MODEL})"
            .value=${this.model}
            @input=${this.onModelInput}
            class="${inputCls} w-40 shrink-0"
          />
          <input
            type="text"
            placeholder="Prompt the AI…"
            .value=${this.prompt}
            @input=${this.onPromptInput}
            class="${inputCls} flex-1"
          />
          ${this.streaming
            ? html`
                <button
                  type="button"
                  @click=${this.onStop}
                  class="px-3 py-1 rounded bg-red-600 text-white text-sm hover:bg-red-700"
                >
                  Stop
                </button>
              `
            : html`
                <button
                  type="submit"
                  ?disabled=${!this.apiKey || !this.endpoint || !this.prompt}
                  class="px-3 py-1 rounded bg-blue-600 text-white text-sm hover:bg-blue-700 disabled:opacity-40 disabled:cursor-not-allowed"
                >
                  Generate
                </button>
              `}
        </div>
      </form>
    `
  }
}

export function registerLitAiStreamContentToolbar(): void {
  if (customElements.get('lit-ai-stream-content-toolbar')) return
  customElements.define('lit-ai-stream-content-toolbar', LitAiStreamContentToolbar)
}

declare global {
  interface HTMLElementTagNameMap {
    'lit-ai-stream-content-toolbar': LitAiStreamContentToolbar
  }
}
